/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CursosIndexRouteImport } from './routes/cursos.index'
import { Route as BolsasIndexRouteImport } from './routes/bolsas.index'
import { Route as CursosSlugRouteImport } from './routes/cursos.$slug'
import { Route as BolsasSlugRouteImport } from './routes/bolsas.$slug'
import { Route as AuthenticatedMinhaContaRouteImport } from './routes/_authenticated/minha-conta'
import { Route as AuthenticatedCheckoutRouteImport } from './routes/_authenticated/checkout'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedPedidosIdRouteImport } from './routes/_authenticated/pedidos.$id'
import { Route as AuthenticatedMeusCursosSlugRouteImport } from './routes/_authenticated/meus-cursos.$slug'
import { Route as AuthenticatedAulaLessonIdRouteImport } from './routes/_authenticated/aula.$lessonId'
import { Route as AuthenticatedAdminPedidosRouteImport } from './routes/_authenticated/admin.pedidos'
import { Route as AuthenticatedAdminBolsasRouteImport } from './routes/_authenticated/admin.bolsas'
import { Route as AuthenticatedAdminAcessosRouteImport } from './routes/_authenticated/admin.acessos'
import { Route as Char91__mockupChar93PreviewSplatRouteImport } from './routes/[__mockup].preview.$'
import { Route as Char91__componentChar93PreviewSplatRouteImport } from './routes/[__component].preview.$'
import { Route as AuthenticatedAdminCursosIndexRouteImport } from './routes/_authenticated/admin.cursos.index'
import { Route as AuthenticatedAdminCursosIdRouteImport } from './routes/_authenticated/admin.cursos.$id'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosIndexRoute = CursosIndexRouteImport.update({
  id: '/cursos/',
  path: '/cursos/',
  getParentRoute: () => rootRouteImport,
} as any)
const BolsasIndexRoute = BolsasIndexRouteImport.update({
  id: '/bolsas/',
  path: '/bolsas/',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosSlugRoute = CursosSlugRouteImport.update({
  id: '/cursos/$slug',
  path: '/cursos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BolsasSlugRoute = BolsasSlugRouteImport.update({
  id: '/bolsas/$slug',
  path: '/bolsas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMinhaContaRoute = AuthenticatedMinhaContaRouteImport.update({
  id: '/minha-conta',
  path: '/minha-conta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCheckoutRoute = AuthenticatedCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPedidosIdRoute = AuthenticatedPedidosIdRouteImport.update({
  id: '/pedidos/$id',
  path: '/pedidos/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeusCursosSlugRoute =
  AuthenticatedMeusCursosSlugRouteImport.update({
    id: '/meus-cursos/$slug',
    path: '/meus-cursos/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAulaLessonIdRoute =
  AuthenticatedAulaLessonIdRouteImport.update({
    id: '/aula/$lessonId',
    path: '/aula/$lessonId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPedidosRoute =
  AuthenticatedAdminPedidosRouteImport.update({
    id: '/admin/pedidos',
    path: '/admin/pedidos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminBolsasRoute =
  AuthenticatedAdminBolsasRouteImport.update({
    id: '/admin/bolsas',
    path: '/admin/bolsas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAcessosRoute =
  AuthenticatedAdminAcessosRouteImport.update({
    id: '/admin/acessos',
    path: '/admin/acessos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const Char91__mockupChar93PreviewSplatRoute =
  Char91__mockupChar93PreviewSplatRouteImport.update({
    id: '/__mockup/preview/$',
    path: '/__mockup/preview/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91__componentChar93PreviewSplatRoute =
  Char91__componentChar93PreviewSplatRouteImport.update({
    id: '/__component/preview/$',
    path: '/__component/preview/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminCursosIndexRoute =
  AuthenticatedAdminCursosIndexRouteImport.update({
    id: '/admin/cursos/',
    path: '/admin/cursos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCursosIdRoute =
  AuthenticatedAdminCursosIdRouteImport.update({
    id: '/admin/cursos/$id',
    path: '/admin/cursos/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/carrinho': typeof CarrinhoRoute
  '/contato': typeof ContatoRoute
  '/sobre': typeof SobreRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/minha-conta': typeof AuthenticatedMinhaContaRoute
  '/bolsas/$slug': typeof BolsasSlugRoute
  '/cursos/$slug': typeof CursosSlugRoute
  '/bolsas/': typeof BolsasIndexRoute
  '/cursos/': typeof CursosIndexRoute
  '/__component/preview/$': typeof Char91__componentChar93PreviewSplatRoute
  '/__mockup/preview/$': typeof Char91__mockupChar93PreviewSplatRoute
  '/admin/acessos': typeof AuthenticatedAdminAcessosRoute
  '/admin/bolsas': typeof AuthenticatedAdminBolsasRoute
  '/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/aula/$lessonId': typeof AuthenticatedAulaLessonIdRoute
  '/meus-cursos/$slug': typeof AuthenticatedMeusCursosSlugRoute
  '/pedidos/$id': typeof AuthenticatedPedidosIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/cursos/$id': typeof AuthenticatedAdminCursosIdRoute
  '/admin/cursos/': typeof AuthenticatedAdminCursosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/carrinho': typeof CarrinhoRoute
  '/contato': typeof ContatoRoute
  '/sobre': typeof SobreRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/minha-conta': typeof AuthenticatedMinhaContaRoute
  '/bolsas/$slug': typeof BolsasSlugRoute
  '/cursos/$slug': typeof CursosSlugRoute
  '/bolsas': typeof BolsasIndexRoute
  '/cursos': typeof CursosIndexRoute
  '/__component/preview/$': typeof Char91__componentChar93PreviewSplatRoute
  '/__mockup/preview/$': typeof Char91__mockupChar93PreviewSplatRoute
  '/admin/acessos': typeof AuthenticatedAdminAcessosRoute
  '/admin/bolsas': typeof AuthenticatedAdminBolsasRoute
  '/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/aula/$lessonId': typeof AuthenticatedAulaLessonIdRoute
  '/meus-cursos/$slug': typeof AuthenticatedMeusCursosSlugRoute
  '/pedidos/$id': typeof AuthenticatedPedidosIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/cursos/$id': typeof AuthenticatedAdminCursosIdRoute
  '/admin/cursos': typeof AuthenticatedAdminCursosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/carrinho': typeof CarrinhoRoute
  '/contato': typeof ContatoRoute
  '/sobre': typeof SobreRoute
  '/_authenticated/checkout': typeof AuthenticatedCheckoutRoute
  '/_authenticated/minha-conta': typeof AuthenticatedMinhaContaRoute
  '/bolsas/$slug': typeof BolsasSlugRoute
  '/cursos/$slug': typeof CursosSlugRoute
  '/bolsas/': typeof BolsasIndexRoute
  '/cursos/': typeof CursosIndexRoute
  '/__component/preview/$': typeof Char91__componentChar93PreviewSplatRoute
  '/__mockup/preview/$': typeof Char91__mockupChar93PreviewSplatRoute
  '/_authenticated/admin/acessos': typeof AuthenticatedAdminAcessosRoute
  '/_authenticated/admin/bolsas': typeof AuthenticatedAdminBolsasRoute
  '/_authenticated/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/_authenticated/aula/$lessonId': typeof AuthenticatedAulaLessonIdRoute
  '/_authenticated/meus-cursos/$slug': typeof AuthenticatedMeusCursosSlugRoute
  '/_authenticated/pedidos/$id': typeof AuthenticatedPedidosIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/cursos/$id': typeof AuthenticatedAdminCursosIdRoute
  '/_authenticated/admin/cursos/': typeof AuthenticatedAdminCursosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/carrinho'
    | '/contato'
    | '/sobre'
    | '/checkout'
    | '/minha-conta'
    | '/bolsas/$slug'
    | '/cursos/$slug'
    | '/bolsas/'
    | '/cursos/'
    | '/__component/preview/$'
    | '/__mockup/preview/$'
    | '/admin/acessos'
    | '/admin/bolsas'
    | '/admin/pedidos'
    | '/aula/$lessonId'
    | '/meus-cursos/$slug'
    | '/pedidos/$id'
    | '/admin/'
    | '/admin/cursos/$id'
    | '/admin/cursos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/carrinho'
    | '/contato'
    | '/sobre'
    | '/checkout'
    | '/minha-conta'
    | '/bolsas/$slug'
    | '/cursos/$slug'
    | '/bolsas'
    | '/cursos'
    | '/__component/preview/$'
    | '/__mockup/preview/$'
    | '/admin/acessos'
    | '/admin/bolsas'
    | '/admin/pedidos'
    | '/aula/$lessonId'
    | '/meus-cursos/$slug'
    | '/pedidos/$id'
    | '/admin'
    | '/admin/cursos/$id'
    | '/admin/cursos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/carrinho'
    | '/contato'
    | '/sobre'
    | '/_authenticated/checkout'
    | '/_authenticated/minha-conta'
    | '/bolsas/$slug'
    | '/cursos/$slug'
    | '/bolsas/'
    | '/cursos/'
    | '/__component/preview/$'
    | '/__mockup/preview/$'
    | '/_authenticated/admin/acessos'
    | '/_authenticated/admin/bolsas'
    | '/_authenticated/admin/pedidos'
    | '/_authenticated/aula/$lessonId'
    | '/_authenticated/meus-cursos/$slug'
    | '/_authenticated/pedidos/$id'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/cursos/$id'
    | '/_authenticated/admin/cursos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CarrinhoRoute: typeof CarrinhoRoute
  ContatoRoute: typeof ContatoRoute
  SobreRoute: typeof SobreRoute
  BolsasSlugRoute: typeof BolsasSlugRoute
  CursosSlugRoute: typeof CursosSlugRoute
  BolsasIndexRoute: typeof BolsasIndexRoute
  CursosIndexRoute: typeof CursosIndexRoute
  Char91__componentChar93PreviewSplatRoute: typeof Char91__componentChar93PreviewSplatRoute
  Char91__mockupChar93PreviewSplatRoute: typeof Char91__mockupChar93PreviewSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos/': {
      id: '/cursos/'
      path: '/cursos'
      fullPath: '/cursos/'
      preLoaderRoute: typeof CursosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bolsas/': {
      id: '/bolsas/'
      path: '/bolsas'
      fullPath: '/bolsas/'
      preLoaderRoute: typeof BolsasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos/$slug': {
      id: '/cursos/$slug'
      path: '/cursos/$slug'
      fullPath: '/cursos/$slug'
      preLoaderRoute: typeof CursosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bolsas/$slug': {
      id: '/bolsas/$slug'
      path: '/bolsas/$slug'
      fullPath: '/bolsas/$slug'
      preLoaderRoute: typeof BolsasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/minha-conta': {
      id: '/_authenticated/minha-conta'
      path: '/minha-conta'
      fullPath: '/minha-conta'
      preLoaderRoute: typeof AuthenticatedMinhaContaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checkout': {
      id: '/_authenticated/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof AuthenticatedCheckoutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pedidos/$id': {
      id: '/_authenticated/pedidos/$id'
      path: '/pedidos/$id'
      fullPath: '/pedidos/$id'
      preLoaderRoute: typeof AuthenticatedPedidosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meus-cursos/$slug': {
      id: '/_authenticated/meus-cursos/$slug'
      path: '/meus-cursos/$slug'
      fullPath: '/meus-cursos/$slug'
      preLoaderRoute: typeof AuthenticatedMeusCursosSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aula/$lessonId': {
      id: '/_authenticated/aula/$lessonId'
      path: '/aula/$lessonId'
      fullPath: '/aula/$lessonId'
      preLoaderRoute: typeof AuthenticatedAulaLessonIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/pedidos': {
      id: '/_authenticated/admin/pedidos'
      path: '/admin/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AuthenticatedAdminPedidosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/bolsas': {
      id: '/_authenticated/admin/bolsas'
      path: '/admin/bolsas'
      fullPath: '/admin/bolsas'
      preLoaderRoute: typeof AuthenticatedAdminBolsasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/acessos': {
      id: '/_authenticated/admin/acessos'
      path: '/admin/acessos'
      fullPath: '/admin/acessos'
      preLoaderRoute: typeof AuthenticatedAdminAcessosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/__mockup/preview/$': {
      id: '/__mockup/preview/$'
      path: '/__mockup/preview/$'
      fullPath: '/__mockup/preview/$'
      preLoaderRoute: typeof Char91__mockupChar93PreviewSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__component/preview/$': {
      id: '/__component/preview/$'
      path: '/__component/preview/$'
      fullPath: '/__component/preview/$'
      preLoaderRoute: typeof Char91__componentChar93PreviewSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/cursos/': {
      id: '/_authenticated/admin/cursos/'
      path: '/admin/cursos'
      fullPath: '/admin/cursos/'
      preLoaderRoute: typeof AuthenticatedAdminCursosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/cursos/$id': {
      id: '/_authenticated/admin/cursos/$id'
      path: '/admin/cursos/$id'
      fullPath: '/admin/cursos/$id'
      preLoaderRoute: typeof AuthenticatedAdminCursosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCheckoutRoute: typeof AuthenticatedCheckoutRoute
  AuthenticatedMinhaContaRoute: typeof AuthenticatedMinhaContaRoute
  AuthenticatedAdminAcessosRoute: typeof AuthenticatedAdminAcessosRoute
  AuthenticatedAdminBolsasRoute: typeof AuthenticatedAdminBolsasRoute
  AuthenticatedAdminPedidosRoute: typeof AuthenticatedAdminPedidosRoute
  AuthenticatedAulaLessonIdRoute: typeof AuthenticatedAulaLessonIdRoute
  AuthenticatedMeusCursosSlugRoute: typeof AuthenticatedMeusCursosSlugRoute
  AuthenticatedPedidosIdRoute: typeof AuthenticatedPedidosIdRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminCursosIdRoute: typeof AuthenticatedAdminCursosIdRoute
  AuthenticatedAdminCursosIndexRoute: typeof AuthenticatedAdminCursosIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCheckoutRoute: AuthenticatedCheckoutRoute,
  AuthenticatedMinhaContaRoute: AuthenticatedMinhaContaRoute,
  AuthenticatedAdminAcessosRoute: AuthenticatedAdminAcessosRoute,
  AuthenticatedAdminBolsasRoute: AuthenticatedAdminBolsasRoute,
  AuthenticatedAdminPedidosRoute: AuthenticatedAdminPedidosRoute,
  AuthenticatedAulaLessonIdRoute: AuthenticatedAulaLessonIdRoute,
  AuthenticatedMeusCursosSlugRoute: AuthenticatedMeusCursosSlugRoute,
  AuthenticatedPedidosIdRoute: AuthenticatedPedidosIdRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminCursosIdRoute: AuthenticatedAdminCursosIdRoute,
  AuthenticatedAdminCursosIndexRoute: AuthenticatedAdminCursosIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CarrinhoRoute: CarrinhoRoute,
  ContatoRoute: ContatoRoute,
  SobreRoute: SobreRoute,
  BolsasSlugRoute: BolsasSlugRoute,
  CursosSlugRoute: CursosSlugRoute,
  BolsasIndexRoute: BolsasIndexRoute,
  CursosIndexRoute: CursosIndexRoute,
  Char91__componentChar93PreviewSplatRoute:
    Char91__componentChar93PreviewSplatRoute,
  Char91__mockupChar93PreviewSplatRoute: Char91__mockupChar93PreviewSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
